#!/bin/bash

TEST_FILES_DIRECTORY="./exemples"

./recompile || { echo "Erreur de compilation"; exit 1; }

for file in ${TEST_FILES_DIRECTORY}/*
do 
	file_name=$(basename $file)
	if [[ -f $file ]]
	then
		echo "## Test <$file_name>"
		java EssaiGraphe "$file"
		echo ""
	fi
done

